# Generated by Django 5.1.7 on 2025-04-09 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_remove_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_date',
        ),
    ]
