# Generated by Django 5.1.7 on 2025-04-09 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_chekout'),
        ('product', '0038_remove_keybord_brand_remove_review_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chekout',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='chekout',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
