# Generated by Django 5.1.7 on 2025-04-09 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_remove_chekout_total_amount_chekout_product'),
        ('product', '0038_remove_keybord_brand_remove_review_product_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chekout',
            new_name='Orderitem',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='product',
            new_name='product_name',
        ),
    ]
