# Generated by Django 5.1.7 on 2025-04-09 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_rename_chekout_orderitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='transaction_id',
        ),
    ]
