# Generated by Django 5.1.7 on 2025-04-09 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_remove_orderitem_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
    ]
