# Generated by Django 5.1.7 on 2025-04-14 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_remove_orderitem_product_name_order_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_name',
        ),
    ]
