# Generated by Django 5.1.7 on 2025-04-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_orderitem_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('success', 'Success')], max_length=20),
        ),
    ]
