# Generated by Django 5.1.7 on 2025-04-21 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0018_remove_order_cart_remove_orderitem_order_and_more'),
        ('product', '0038_remove_keybord_brand_remove_review_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='quantity',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='cart',
            field=models.ManyToManyField(to='product.cart'),
        ),
    ]
