# Generated by Django 5.1.7 on 2025-04-21 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0020_remove_orderitem_cart_orderitem_product_name_and_more'),
        ('product', '0038_remove_keybord_brand_remove_review_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='cart',
            field=models.ManyToManyField(to='product.cart'),
        ),
    ]
