# Generated by Django 5.1.7 on 2025-04-21 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0022_checkout_delete_order_remove_orderitem_cart_and_more'),
        ('product', '0038_remove_keybord_brand_remove_review_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='user',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='cart',
            field=models.ManyToManyField(to='product.cart'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='checkout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.checkout'),
        ),
    ]
