# Generated by Django 5.1.7 on 2025-04-21 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0023_remove_orderitem_user_orderitem_cart_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='user',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='checkout',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product_name',
        ),
    ]
