# Generated by Django 5.1.7 on 2025-04-21 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0025_remove_orderitem_cart_orderitem_product_name_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
