# Generated by Django 5.1.7 on 2025-04-21 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0026_delete_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='checkout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payment.checkout'),
        ),
    ]
