# Generated by Django 5.1.7 on 2025-04-23 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0028_checkout_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='user',
        ),
    ]
