# Generated by Django 5.2 on 2025-05-06 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0030_orderitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='checkout',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_name',
            field=models.CharField(default='BMW', max_length=255),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='checkout',
            field=models.ManyToManyField(blank=True, related_name='items', to='payment.checkout'),
        ),
    ]
